{{- with .Values.remoteDataLoader.autoscaling -}}
{{- if .enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: remote-data-loader
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: remote-data-loader
  minReplicas: {{ .minReplicas }}
  maxReplicas: {{ .minReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .averageCpuUtilization }}
{{- end -}}
{{- end -}}
