apiVersion: v1
kind: Service
metadata:
  name: remote-data-loader
  annotations:
    {{- range $key, $value := .Values.remoteDataLoader.service.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  selector:
    app: remote-data-loader
  ports:
    - name: controller
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: metrics
      protocol: TCP
      port: 6001
      targetPort: 6001
