apiVersion: v1
kind: Service
metadata:
  name: external-connector
  annotations:
    {{- range $key, $value := .Values.externalConnector.service.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  selector:
    app: external-connector
  ports:
    - name: controller
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: metrics
      protocol: TCP
      port: 6001
      targetPort: 6001
